[project]
name = "bookworm-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=2.11.1",
    "pyinstaller>=6.12.0",
    "pywebview>=5.4",
]
